### ISSUE TITLE
Add to Marketplace

### ISSUE THREAD

**Issue by kevinpapst** [dexterity42/SharedProjectTimesheetsBundle#10]
This plugin is too good to be hidden in GitHub.

Please consider to add it to the marketplace.

Read how: https://www.kimai.org/documentation/plugins.html#list-your-plugin-in-the-marketplace

**Comment by dexterity42** [comment]
I think i'll be able to release the first version until next week. Then i'll add it to the marketplace 👍🏻

**Comment by dexterity42** [comment]
PR to add plugin to marketplace: https://github.com/kimai/www.kimai.org/pull/84

**Comment by kevinpapst** [comment]
Merged and live:
https://www.kimai.org/store/vettersolutions-shared-project-timesheets-bundle.html

👍
