### ISSUE TITLE
database migration error

### ISSUE THREAD

**Issue by BeckeBauer** [dexterity42/SharedProjectTimesheetsBundle#16]
I tried to install the plugin but got the following error:

```Migration 2020120600000 failed during Execution. Error Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.```

```[ERROR] Failed to install SharedProjectTimesheetsBundle database: Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.```

I am using MariaDB. Any idea how to solve the issue?

**Comment by dexterity42** [comment]
Hi @BeckeBauer, i'm sorry to hear that you have problems installing the plugin. Sadly its a little confusing, as none of the migrations are using the enum type. In addition, the `MariaDb1027Platform` only extends the `MysqlPlatform` which is the one i've tested the migrations with.

Could you please try if the following settings solve the issue: https://symfony.com/doc/current/doctrine/dbal.html#registering-custom-mapping-types-in-the-schematool

Looking forward to your reply.

**Comment by BeckeBauer** [comment]
Added the suggested entries to my local.yaml, reloaded the cache and voila, installation went trough smoothly:

![pic](https://user-images.githubusercontent.com/51003649/108095092-ca2c7200-707f-11eb-9f3f-6a40cf2474ed.png)

Thanks for the help

**Comment by dexterity42** [comment]
Good to know - thanks for your response and for closing the issue!
