### ISSUE TITLE
Kimai 2.0 support

### ISSUE THREAD

**Issue by m-narita-s-style** [dexterity42/SharedProjectTimesheetsBundle#35]
Hello.

I am a heavy user of this feature.

My company uses this feature to inform our clients of our work status and it has been very helpful.

So I am hesitant to upgrade Kimai until this feature is supported by Kimai 2.0.

It would be very nice if you could support Kimai 2.0!

**Comment by kevinpapst** [comment]
Upgraded, see here: https://github.com/Keleo/SharedProjectTimesheetsBundle

**Comment by m-narita-s-style** [comment]
Thanks!

Upgrade to Kimai 2.0 and try out the features right away!
